### ISSUE TITLE
Feedback and Questions on JV_VrayToGLB.ms

### ISSUE THREAD

**Issue by Yason83** [jmdvella/3dsmax-scripts#5]
Dear @jmdvella,

Thank you very much for your plugin; you've done essential work. The script converts Vray materials better than any other.

I have a few remarks, could you please take a look and perhaps find a solution? I also don’t exclude the possibility that I may have made mistakes in the settings somewhere.

1. The UV coordinates are mirrored, possibly related to Y-up.
2. The NormalMap is not displayed correctly if it is set up in Vray as black and white.
3. The roughness parameter is not transferred.

Additionally, I have attached the original 3Ds Max project and the resulting glb file for your review.  (140Mb )
https://www.dropbox.com/scl/fi/av8o0yhkbokm82a4hxbs0/VZ.zip?rlkey=xq3uuysjfzcdwhi3e1ubh8utc&dl=0

Thank you in advance for your time and assistance.
![2023-11-01_211535](https://github.com/jmdvella/3dsmax-scripts/assets/32398829/e66c71a7-cc20-4565-aaff-f7cf20405ff5)
![2023-11-01_211214](https://github.com/jmdvella/3dsmax-scripts/assets/32398829/02b11c3b-7b3d-471d-bfc0-fd0dfb1d177f).

Best regards,

**Comment by Yason83** [comment]
From what I understand, the glTF format no longer supports BumpMaps. This development https://github.com/Mehdi-Antoine/NormalMapGenerator does an excellent job of converting BumpMaps into NormalMaps. Could you arrange something similar for bump maps?

**Comment by jmdvella** [comment]
Hi @Yason83 ,

1. Your UVs are mirrored on your palm leaf model. Adjust the UV so that they are layed out flat like the other 4 plants: https://ibb.co/nmWccbd
2. Make sure all your Bump textures are converted to Normal. You can do this with Substance Painter/Designer or other software: https://ibb.co/cQBqrQC
3. You are not using any Roughness textures in your 3Dsmax scene. All your materials are currently using glossiness so invert all your glossiness textures and set the mode to Roughness in the vray material: https://ibb.co/5sW3M4T 
Take note, GLB doesn't use roughness parameters (should be set to 1.0). This means you will also have to adjust the roughness textures to suit the parameter adjustment. With PBR/GLB everything is driven from the bitmap (same with all other channels). Also make sure you invert the glossiness bitmap itself, don't use a color correction node or similar. 

Also all your models are missing textures, open your GLB in windows 3D viewer and check (1) all channels (2) and make sure none of the textures are red/white stripes (missing): https://ibb.co/VBMBh4x
You need a minimum of albedo, roughness, normal, metallic, ambient occlusion for it to work correctly as GLB (for all materials!). All other channels are optional.

FYI, maybe you have already but check the youtube video to make sure your textures/materials match the expected output for GLB: https://youtu.be/BwUq_Vws3M0?si=zDxX2FQ5F8zkPr9R
